[general]
static=yes
writeprotect=no

[default]
exten => _X.,1,NoOp(Test call to ${EXTEN})
 same => n,Answer()
 same => n,Playback(hello-world)
 same => n,Hangup()

exten => 100,1,Answer()
 same => n,Playback(hello-world)
 same => n,Hangup()
