options {
    directory "/var/cache/bind";
    listen-on { any; };
    listen-on-v6 { any; };
    allow-query { any; };
    allow-recursion { any; };
    recursion yes;
    dnssec-validation no;
};

zone "test.local" {
    type master;
    file "/etc/bind/zones/test.local.zone";
};

zone "example.test" {
    type master;
    file "/etc/bind/zones/example.test.zone";
};
